name: flutter_application_w5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  contacts_service: ^0.6.3
  telephony: ^0.2.0
  permission_handler: ^10.4.5  # Giữ nguyên phiên bản này cho tương thích



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
